# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
