# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 23:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('skill_type', models.CharField(choices=[('TH', 'Technology'), ('PL', 'Programming Language'), ('OS', 'Operating System'), ('ST', 'Software Tool'), ('FR', 'Framework')], max_length=2)),
            ],
        ),
    ]
