# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 01:20
from __future__ import unicode_literals

import apps.skills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.skills.models.image_upload_to),
        ),
    ]
