# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20170411_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='projects.Project'),
        ),
    ]
