# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_auto_20170411_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='project',
        ),
    ]
